// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmveZHrbhmqXOxB7WCu00g1LknxtPwliE',
    appId: '1:465068269461:web:c2dff33702ad137c78609c',
    messagingSenderId: '465068269461',
    projectId: 'flutter-app-distribution-d662b',
    authDomain: 'flutter-app-distribution-d662b.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-d662b.appspot.com',
    measurementId: 'G-7QFB075ZBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADkV6dg1_EBD3tJ6sTiVZqQNCkNa0EXXI',
    appId: '1:465068269461:android:17250f491668f6e378609c',
    messagingSenderId: '465068269461',
    projectId: 'flutter-app-distribution-d662b',
    storageBucket: 'flutter-app-distribution-d662b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABTlExPIG-pYVU8G9jZKbDfULIL39RYFo',
    appId: '1:465068269461:ios:a2e8c63beb3e776d78609c',
    messagingSenderId: '465068269461',
    projectId: 'flutter-app-distribution-d662b',
    storageBucket: 'flutter-app-distribution-d662b.appspot.com',
    iosBundleId: 'com.example.docAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABTlExPIG-pYVU8G9jZKbDfULIL39RYFo',
    appId: '1:465068269461:ios:6b004dbf4fa96a7078609c',
    messagingSenderId: '465068269461',
    projectId: 'flutter-app-distribution-d662b',
    storageBucket: 'flutter-app-distribution-d662b.appspot.com',
    iosBundleId: 'com.example.docAppointment.RunnerTests',
  );
}
